# Generated by Django 5.1.7 on 2025-03-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
