# Generated by Django 5.1.7 on 2025-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chicken',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chicken',
            name='health_status',
            field=models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Injured', 'Injured')], max_length=20),
        ),
        migrations.AddField(
            model_name='chicken',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
