# Generated by Django 5.1.7 on 2025-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_sale_chicken_variety_alter_sale_chicken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='variety',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='egg_variety',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
