# Generated by Django 5.1.7 on 2025-03-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_chicken_age_chicken_breed_chicken_health_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicken',
            name='breed',
        ),
    ]
