# Generated by Django 5.1.7 on 2025-03-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_egg_variety_sale_egg_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='price_per_egg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='egg',
            name='variety',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('brown', 'Brown'), ('organic', 'Organic'), ('free_range', 'Free Range')], max_length=20, null=True),
        ),
    ]
