# Generated by Django 5.1.7 on 2025-03-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_remove_chicken_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicken',
            name='age',
        ),
        migrations.RemoveField(
            model_name='chicken',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='chicken',
            name='weight',
        ),
        migrations.AlterField(
            model_name='chicken',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
